import sys
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QMainWindow, QAbstractItemView, QListWidgetItem
from ui.ui_main_window import Ui_MainWindow
from logic.flashcard_logic import FlashcardLogic

#


class MainWindow(QMainWindow, Ui_MainWindow):
    '''
    Main window class for Flashcard application
    Handles UI interactions and connects user inputs to the back-end logic
    '''

    def __init__(self) -> None:
        '''
        Initializes UI, sets up widget properties like WordWrap,
        connects buttons to their respective functions, and loads existing flashcards
        '''
        super().__init__()
        # standard initialization for the UI generated by Qt Designer
        self.setupUi(self)
        
        # Enable multi-line text for long definitions and center the text
        self.label_display.setWordWrap(True)
        self.label_display.setAlignment(Qt.AlignmentFlag.AlignCenter)
        
        # Allow editing of added cards by double-clicking
        # Wrap long terms and definitions
        self.card_list_widget.setEditTriggers(QAbstractItemView.EditTrigger.DoubleClicked)
        self.card_list_widget.setWordWrap(True)

        # Connect button signals to respective handler functions
        self.button_study.clicked.connect(self.start_study)
        self.button_add.clicked.connect(self.add_card)
        self.button_next.clicked.connect(self.show_next_card)
        self.button_flip.clicked.connect(self.flip_card)
        self.button_restart.clicked.connect(self.restart_study)
        self.label_term.setText('Term')
        
        # Initial UI state setup
        self.statusBar().showMessage("Ready")
        self.logic = FlashcardLogic()
        self.update_list_view()


    def add_card(self) -> None:
        '''
        Gets text from term and definition input fields, sends to logic handler,
        for saving, and updates list view
        '''
        # Pull raw strings from the input fields
        term = self.input_term.text()
        definition = self.input_definition.text()

        # Adds card through logic
        # Returns True if validation passes
        if self.logic.add_card(term, definition):
            self.input_term.clear()
            self.input_definition.clear()
            self.statusBar().showMessage("Card added successfully", 2000)
            self.update_list_view()


    def start_study(self) -> None:
        '''
        Starts study sessions by getting the current flashcard from logic
        and showing the term on the main display label
        '''
        # Ensure we are at the beginning of set
        self.logic.current_index = 0

        # Request first card from logic handler
        card = self.logic.get_current_card()
        if card:
            # Display only the 'term' to start the session
            self.label_display.setText(card['term'])
            self.statusBar().showMessage("Study started")
        else:
            # If the user clicks 'Start' with an empty list, a message appears
            self.statusBar().showMessage("Please add a card first.")


    def show_next_card(self) -> None:
        '''
        Advances flashcard index in the logic handler and updates the display label
        to show the next term in the set
        '''
        # Tell logic to move index forward
        self.logic.next_card()

        # Get and display card at new index
        card = self.logic.get_current_card()
        if card:
            # Update display to next term
            self.label_display.setText(card['term'])


    def flip_card(self) -> None:
        '''
        Toggles display between the current card's term and definition
        by asking for the 'flipped' text from the logic handler
        '''
        # Get what is currently visible on the display label
        current_text = self.label_display.text()

        # Handles toggle between term and definition
        new_text = self.logic.get_flipped_text(current_text)
        
        if new_text:
            self.label_display.setText(new_text)


    def restart_study(self) -> None:
        '''
        Resets index and updates display to the first card
        '''
        # Tell logic handler to set current index back to 0
        self.logic.reset_session()
        
        # Get card at the reset index so the first card
        card = self.logic.get_current_card()
        
        if card:
            # Update main display label to show the first term again
            self.label_display.setText(card['term'])
             
            self.statusBar().showMessage("Session restarted",2000)


    def update_list_view(self) -> None:
        '''
        Clears side list widget and repopulates with all currently saved cards,
        sorted alphabetically by term
        Enables editing flags for each item
        '''
        self.card_list_widget.clear()
        all_cards = self.logic.get_all_cards()
        
        # Sort added cards alphabetically
        sorted_cards = sorted(all_cards, key = lambda x: x['term'].lower())
       
        for card in sorted_cards:
            display_text = f"{card['term']} : {card['definition']}"
            item = QListWidgetItem(display_text)
            
            # Let item be edited
            item.setFlags(item.flags() | Qt.ItemFlag.ItemIsEditable)
            self.card_list_widget.addItem(item)

        # Lines 141 to 147 was adapted with the help of Google Gemini


if __name__ == "__main__":
    # Initialize the application, display the window, and start event loop
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())