# Form implementation generated from reading ui file 'ui/flash.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_term = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_term.setGeometry(QtCore.QRect(60, 120, 113, 21))
        self.input_term.setObjectName("input_term")
        self.input_definition = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_definition.setGeometry(QtCore.QRect(60, 180, 113, 21))
        self.input_definition.setObjectName("input_definition")
        self.button_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(50, 270, 101, 31))
        self.button_add.setObjectName("button_add")
        self.label_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_display.setGeometry(QtCore.QRect(500, 90, 101, 81))
        self.label_display.setObjectName("label_display")
        self.button_flip = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_flip.setGeometry(QtCore.QRect(510, 230, 75, 24))
        self.button_flip.setObjectName("button_flip")
        self.button_next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_next.setGeometry(QtCore.QRect(510, 280, 75, 24))
        self.button_next.setObjectName("button_next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_add.setText(_translate("MainWindow", "Add Card"))
        self.label_display.setText(_translate("MainWindow", "TextLabel"))
        self.button_flip.setText(_translate("MainWindow", "PushButton"))
        self.button_next.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
